### ISSUE TITLE
Crash on string-valued route_type

### ISSUE THREAD

**Issue by r-barnes** [remix/partridge#64]
* partridge version: 1.1.1
* Python version: 3.7.5
* Operating System: Lubuntu 19.10

### Description

I am running the commands
```python
feed = ptg.load_feed(gtfs_filename)
return feed.routes.route_type.isin([3,4,5]).any()
```
on the file `https://transitfeeds.com/p/traveline/1033/latest/download` which contains:
```
route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,route_sort_order
21-L16-U-y05-51704,OId_CX,C,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford",3,,,,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford"
21-L16-U-y05-51705,OId_CX,C,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford",3,,,,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford"
21-L16-U-y05-51706,OId_CX,C,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford",3,,,,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford"
21-L16-U-y05-51707,OId_CX,C,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford",3,,,,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford"
21-L16-U-y05-51708,OId_CX,C,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford",3,,,,"Stratford - Manor Park - Ilford - Seven Kings - Goodmayes - Romford"
21-L40-U-y05-51801,OId_CX,L3,"Hackney Downs/Liverpool Street - Walthamstow Central - Chingford",3,,,,"Hackney Downs/Liverpool Street - Walthamstow Central - Chingford"
21-L40-U-y05-51802,OId_CX,L3,"Hackney Downs/Liverpool Street - Walthamstow Central - Chingford",3,,,,"Hackney Downs/Liverpool Street - Walthamstow Central - Chingford"
21-L40-U-y05-51803,OId_CX,L3,"Hackney Downs/Liverpool Street - Walthamstow Central - Chingford",3,,,,"Hackney Downs/Liverpool Street - Walthamstow Central - Chingford"
21-L40-U-y05-51804,OId_CX,L3,"Hackney Downs/Liverpool Street - Walthamstow Central - Chingford",3,,,,"Hackney Downs/Liverpool Street - Walthamstow Central - Chingford"
21-L50-U-y05-51624,OId_CX,L1,"Seven Sisters - Bruce Grove - White Hart Lane - Edmonton Green - Enfield Town",3,,,,"Seven Sisters - Bruce Grove - White Hart Lane - Edmonton Green - Enfield Town"
21-N3-_-y05-49270,OId_CX,N3,"Oxford Circus - Crystal Palace - Bromley North",3,,,,"Oxford Circus - Crystal Palace - Bromley North"
21-N68-_-y05-46245,OId_CX,N68,"Old Coulsdon - Croydon - Norwood - Herne Hill - Camberwell - Waterloo - Tottenham Court Road",3,,,,"Old Coulsdon - Croydon - Norwood - Herne Hill - Camberwell - Waterloo - Tottenham Court Road"
21-P13-_-y05-51679,OId_CX,P13,"Streatham - Peckham - New Cross Gate",3,,,,"Streatham - Peckham - New Cross Gate"
21-R70-_-y05-50173,OId_TE,R70,"Hampton, The Avenue - Hampton - Fulwell - Twickenham - Richmond, Manor Circus",3,,,,"Hampton, The Avenue - Hampton - Fulwell - Twickenham - Richmond, Manor Circus"
21-S4-_-y05-50957,OId_CX,S4,"Roundshaw - Sutton - St Helier",3,,,,"Roundshaw - Sutton - St Helier"
21-U5-_-y05-49629,OId_TE,U5,"Uxbridge - Cowley - Hillingdon Hospital - West Drayton - Stockley Park - Hayes & Harlington Station",3,,,,"Uxbridge - Cowley - Hillingdon Hospital - West Drayton - Stockley Park - Hayes & Harlington Station"
21-U7-_-y05-49631,OId_TE,U7,"Uxbridge - Hillingdon Hospital - Charville School - Hayes, Sainsbury's",3,,,,"Uxbridge - Hillingdon Hospital - Charville School - Hayes, Sainsbury's"
21-U9-_-y05-49448,OId_TE,U9,"Uxbridge - Ickenham - Harefield",3,,,,"Uxbridge - Ickenham - Harefield"
25-DLR-_-y05-10,OId_DLR,DLR,"Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal"
25-DLR-_-y05-11,OId_DLR,DLR,"Bank/Tower Gateway/Stratford International - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Bank/Tower Gateway/Stratford International - Beckton/Lewisham/Woolwich Arsenal"
25-DLR-_-y05-13,OId_DLR,DLR,"Tower Gateway/Stratford International/Bow Church - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Tower Gateway/Stratford International/Bow Church - Beckton/Lewisham/Woolwich Arsenal"
25-DLR-_-y05-16,OId_DLR,DLR,"Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal"
25-DLR-_-y05-17,OId_DLR,DLR,"Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal"
25-DLR-_-y05-18,OId_DLR,DLR,"Bank/Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Bank/Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal"
25-DLR-_-y05-19,OId_DLR,DLR,"Bank/Tower Gateway/Stratford/Stratford Interntional - Beckton/Woolwich Arsenal // Island Gardens - Lewisham",undefined,,,,"Bank/Tower Gateway/Stratford/Stratford Interntional - Beckton/Woolwich Arsenal // Island Gardens - Lewisham"
25-DLR-_-y05-20,OId_DLR,DLR,"Bank/Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Bank/Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal"
25-DLR-_-y05-3,OId_DLR,DLR,"Bank/Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Bank/Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal"
25-DLR-_-y05-8,OId_DLR,DLR,"Bank/Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal",undefined,,,,"Bank/Tower Gateway/Stratford/Stratford International - Beckton/Lewisham/Woolwich Arsenal"
30-CR-_-y05-19,OId_CRC,Circular Cruise Westminster,"Westminster - St Katharines - Westminster",4,,,,"Westminster - St Katharines - Westminster"
31-TRS-_-y05-20,OId_TRS,Thames River Services,"Westminster - St Katherine's - Greenwich",4,,,,"Westminster - St Katherine's - Greenwich"
32-CCR-_-y05-24,OId_CCR,City Cruises,"Westminster - Greenwich",4,,,,"Westminster - Greenwich"
33-RB1-_-y05-26,OId_CV,RB1,"Royal Arsenal Woolwich - Canary Wharf - Embankment - Battersea Power Station",4,,,,"Royal Arsenal Woolwich - Canary Wharf - Embankment - Battersea Power Station"
33-RB1-X-y05-9,OId_CV,RB1X,"Royal Arsenal Woolwich - Canary Wharf - Embankment - Westminster",4,,,,"Royal Arsenal Woolwich - Canary Wharf - Embankment - Westminster"
33-RB2-_-y05-17,OId_CV,RB2,"London Bridge - Embankment - Bankside",4,,,,"London Bridge - Embankment - Bankside"
```
Note that the `route_type` column contains a string `undefined`.

This causes a crash:
```
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 1897, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "undefined"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/pull_gtfs.py", line 271, in <module>
    ValidateFeeds(feeds_db_filename, data_template_name, parsed_prefix)
  File "./src/pull_gtfs.py", line 242, in ValidateFeeds
    fm.validate_feeds(parsed_prefix)
  File "./src/pull_gtfs.py", line 206, in validate_feeds
    self.validate_feed(fid, parsed_prefix)
  File "./src/pull_gtfs.py", line 190, in validate_feed
    elif not parse_gtfs.HasBusRoutes(filename):
  File "/home/rick/projects/RISE_ev_bus/dispatch/src/parse_gtfs.py", line 365, in HasBusRoutes
    return feed.routes.route_type.isin(route_types).any()
  File "/home/rick/projects/RISE_ev_bus/dispatch/env/lib/python3.7/site-packages/partridge/gtfs.py", line 16, in getter
    return self.get(filename)
  File "/home/rick/projects/RISE_ev_bus/dispatch/env/lib/python3.7/site-packages/partridge/gtfs.py", line 51, in get
    self._convert_types(filename, df)
  File "/home/rick/projects/RISE_ev_bus/dispatch/env/lib/python3.7/site-packages/partridge/gtfs.py", line 164, in _convert_types
    df[col] = converter(df[col])
  File "/home/rick/projects/RISE_ev_bus/dispatch/env/lib/python3.7/site-packages/pandas/core/tools/numeric.py", line 151, in to_numeric
    values, set(), coerce_numeric=coerce_numeric
  File "pandas/_libs/lib.pyx", line 1934, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "undefined" at position 1804
```

Passing the above data through pandas directly:
```python3
#!/usr/bin/env python3
import pandas as pd
a=pd.read_csv("routes.txt")
route_types = [3,4,5]
a.route_type.isin(route_types).any()
```
does not result in an error.

Therefore, partridge should probably do some kind of sanitizing to ensure that the `route_type` column is actually numeric.

**Comment by r-barnes** [comment]
@nickolasclarke

**Comment by invisiblefunnel** [comment]
Can you update the body of the issue to show how you initialized the feed? Thanks.

**Comment by r-barnes** [comment]
@invisiblefunnel : Done. Was just calling `ptg.load_feed(gtfs_filename)` beforehand.

**Comment by invisiblefunnel** [comment]
> Therefore, partridge should probably do some kind of sanitizing to ensure that the route_type column is actually numeric.

Handling completely wrong values is not within the scope of partridge. If this is critical for your application, I recommend using `load_raw_feed` and applying your own sanitization or just fixing these issues upstream. I know this isn't the answer you wanted, but sanitization and validation are not a goal of this project.
